### ISSUE TITLE
Consider renaming project to comply with naming requirements

### ISSUE THREAD

**Issue by snicoll** [EugeneMsv/amqp-rabbit-spring-boot-autoconfigure#1]
As [defined in the official documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) Spring Boot requests that 3rd party starter does not start with "spring-*". 

Could you please consider renaming this project and the artifact that it produces?

**Comment by EugeneMsv** [comment]
> As [defined in the official documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) Spring Boot requests that 3rd party starter does not start with "spring-*".
> 
> Could you please consider renaming this project and the artifact that it produces?

Is amqp-rabbit-configurator  ok?

**Comment by snicoll** [comment]
Anything that makes it clear that it is third party is fine. If it's a spring boot starter it would be nice if it ended with `spring-boot-starter` thought that's not mandatory.

**Comment by EugeneMsv** [comment]
done
