### ISSUE TITLE
Consider changing the groupId

### ISSUE THREAD

**Issue by snicoll** [EugeneMsv/amqp-rabbit-spring-boot-autoconfigure#2]
Do you have push rights on Maven central for `<groupId>com.amqp.rabbit</groupId>`? If not, I'd change the groupId to something that you have access to.

**Comment by EugeneMsv** [comment]
@snicoll Please tell me where I can find list of available gorupIds?

**Comment by EugeneMsv** [comment]
I've never published to maven central. Is this manual ok https://dzone.com/articles/publish-your-artifacts-to-maven-central ?

**Comment by snicoll** [comment]
The `groupId` should refer to something that "you own" (usually in the form of a reverse domain name). In particular, you should not use the `groupId` of another organization.

`com.github.eugenemsv` is something you could use for instance.

**Comment by EugeneMsv** [comment]
changed to com.github.eugene.msv.amqp.rabbit
