### ISSUE TITLE
Create a root namespace for configuration keys

### ISSUE THREAD

**Issue by snicoll** [EugeneMsv/amqp-rabbit-spring-boot-autoconfigure#3]
Rather than having several namespaces at the root for config (such as `queues`). Please have a root namespace specific to the project to reduce clashes with others.

**Comment by EugeneMsv** [comment]
@snicoll I'm not sure I understand you.

**Comment by snicoll** [comment]
In the README I can see at least configuration keys named `local.*` and `queue.*`. I don't know if the former is something you manage here but it's vague and could be potentially used by an application. While `queue` is more specific, it's still vague in a global context (could be a JMS queue or any sort of custom mechanism).

A starter usually has a "code name" and all keys start with that codename.

**Comment by EugeneMsv** [comment]
Changed to _queue.rabbit_

**Comment by snicoll** [comment]
Namespacing works the other way around I am afraid. First the codename of the project (so that all properties are under that key) then the thing you want to configure. Using `rabbit.queue` doesn't sound legit to me as Rabbit is somewhat a reserved name.

It would really help if you had some sort of name that represents this starter.
