### ISSUE TITLE
good idea!

### ISSUE THREAD

**Issue by rfelgent** [EugeneMsv/amqp-rabbit-spring-boot-autoconfigure#4]
Hello @EugeneMsv ,

the declarative, configuration approach without writing java code is one main reason for me to use "camel-rabbit" over "spring-amqp".

Where can I vote up for this project?!

**Comment by EugeneMsv** [comment]
Hello @rfelgent thank you. I just proposed this project by pull request https://github.com/spring-projects/spring-boot/pull/17537.
